### ISSUE TITLE
Does not work with SSL Enabled

### ISSUE THREAD

**Issue by sbender9** [ieb/sailinstruments#1]
```
[Warning] [blocked] The page at https://xxxx:3443/@ib236/sailinstruments/dist/ was not allowed to run insecure content from ws://xxxxx:3443/signalk/v1/stream. (vendor.6edb0b07854c89ff6dfa.bundle.js, line 38)
```

**Comment by ieb** [comment]
Have fixed however, can't test due to being unable to run the SignalK server on https (node version v12.13.1)

{code}
x43543-2:signalk-server-node ieb$ bin/nmea-from-file
signalk-server running at 0.0.0.0:3443

Redirect server running on port 3000
(node:33902) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
internal/buffer.js:940
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:940:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:181:19)
    at Stream.<anonymous> (/Users/ieb/timefields/nmea2000/signalk/signalk-server-node/node_modules/handle-thing/lib/handle.js:88:10)
    at Stream.emit (events.js:215:7)
    at endReadableNT (/Users/ieb/timefields/nmea2000/signalk/signalk-server-node/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:1077:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
x43543-2:signalk-server-node ieb$ 
{code}

**Comment by ieb** [comment]
caused by https://github.com/spdy-http2/node-spdy/issues/363 with fix in https://github.com/spdy-http2/handle-thing/commit/4e4aae84b96c2b19637fc865b70eed6b15ce7dc5
